### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by NickTehUnicorn**
Tiny but important fixes :P

### CODE REVIEW

**Comment by McpeBooster** [comment]
why did you removed this?

**Comment by NickTehUnicorn** [comment]
Remove what?

**Comment by McpeBooster** [comment]
the changes you made in the pull request

**Comment by NickTehUnicorn** [comment]
I didn't remove it..?
If you're asking why I made the changes, obviously, to fix tiny grammar mistakes.

**Pull request merged**
